name: NETOPIA SDK Validation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 linter
        run: |
          flake8 .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

  release:
    name: Create Release
    if: github.ref_type == 'tag'  # Run only for tag pushes
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Extract tag name
      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            ## What's Changed
            - Automated release for version ${{ env.TAG_NAME }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}